2024-12-16 23:48:22,530 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-16 23:48:22,530 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-16 23:48:26,652 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:26] "GET / HTTP/1.1" 200 -
2024-12-16 23:48:26,735 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:26] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:48:26,782 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:26] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-16 23:48:27,287 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-12-16 23:48:32,142 - INFO - main.py - User 'zura' logged in successfully.
2024-12-16 23:48:32,144 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-16 23:48:32,201 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:32] "GET /index HTTP/1.1" 200 -
2024-12-16 23:48:32,280 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:32] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:48:42,060 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'callsign_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 282, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 192, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'callsign_1'
2024-12-16 23:48:42,125 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:48:42] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-16 23:51:24,285 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:24] "GET / HTTP/1.1" 200 -
2024-12-16 23:51:24,305 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:24] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:51:24,323 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:24] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-16 23:51:29,340 - INFO - main.py - User 'zura' logged in successfully.
2024-12-16 23:51:29,342 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:29] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-16 23:51:29,349 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:29] "GET /index HTTP/1.1" 200 -
2024-12-16 23:51:29,378 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:29] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:51:35,733 - INFO - Insert_to_DBM.py - Using Python interpreter: E:\ZURA KOPADZE\mapping_stca\venv\Scripts\python.exe
2024-12-16 23:51:35,733 - INFO - Insert_to_DBM.py - Script path: E:\ZURA KOPADZE\mapping_stca\DBM\create_Midpoints_Table.py
2024-12-16 23:51:40,356 - INFO - Insert_to_DBM.py - Script executed successfully from path: E:\ZURA KOPADZE\mapping_stca\DBM\create_Midpoints_Table.py
Excel file loaded successfully.
Connected to the database successfully.
Results have been saved to the Midpoints database.

2024-12-16 23:51:40,938 - INFO - main.py - File 'sourse_file.xlsx' uploaded successfully.
2024-12-16 23:51:40,939 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:40] "[32mPOST /upload HTTP/1.1[0m" 302 -
2024-12-16 23:51:40,947 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:40] "GET /index HTTP/1.1" 200 -
2024-12-16 23:51:40,978 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:51:40] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:52:00,220 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'callsign_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 282, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 192, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'callsign_1'
2024-12-16 23:52:00,222 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:52:00] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-16 23:53:57,822 - INFO - main.py - Flask application is shutting down.
2024-12-16 23:54:01,627 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-16 23:54:01,627 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-16 23:54:04,230 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:04] "GET / HTTP/1.1" 200 -
2024-12-16 23:54:04,260 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:04] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:54:04,294 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:04] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-16 23:54:09,036 - INFO - main.py - User 'zura' logged in successfully.
2024-12-16 23:54:09,037 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:09] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-16 23:54:09,055 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:09] "GET /index HTTP/1.1" 200 -
2024-12-16 23:54:09,081 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:09] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:54:18,670 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:18] "POST /index HTTP/1.1" 200 -
2024-12-16 23:54:18,697 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:18] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:54:18,736 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:54:18] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-16 23:55:35,365 - INFO - main.py - Flask application is shutting down.
2024-12-16 23:55:39,406 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-16 23:55:39,406 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-16 23:55:42,308 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:42] "GET / HTTP/1.1" 200 -
2024-12-16 23:55:42,337 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:42] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:55:42,358 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:42] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-16 23:55:47,313 - INFO - main.py - User 'zura' logged in successfully.
2024-12-16 23:55:47,315 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:47] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-16 23:55:47,332 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:47] "GET /index HTTP/1.1" 200 -
2024-12-16 23:55:47,349 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:47] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:55:58,376 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'callsign_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 282, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 192, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'callsign_1'
2024-12-16 23:55:58,383 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:55:58] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-16 23:57:41,456 - INFO - main.py - Flask application is shutting down.
2024-12-16 23:57:44,874 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-16 23:57:44,874 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-16 23:57:47,746 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:47] "GET / HTTP/1.1" 200 -
2024-12-16 23:57:47,775 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:47] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:57:47,793 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:47] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-16 23:57:53,609 - INFO - main.py - User 'zura' logged in successfully.
2024-12-16 23:57:53,610 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:53] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-16 23:57:53,629 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:53] "GET /index HTTP/1.1" 200 -
2024-12-16 23:57:53,655 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:57:53] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:58:02,026 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:02] "POST /index HTTP/1.1" 200 -
2024-12-16 23:58:02,054 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:02] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:58:02,064 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:02] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-16 23:58:53,598 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:53] "POST /index HTTP/1.1" 200 -
2024-12-16 23:58:53,626 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:53] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:58:53,657 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:58:53] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-16 23:59:01,446 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:59:01] "POST /index HTTP/1.1" 200 -
2024-12-16 23:59:01,474 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:59:01] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-16 23:59:01,586 - INFO - _internal.py - 127.0.0.1 - - [16/Dec/2024 23:59:01] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:01:12,803 - INFO - main.py - Flask application is shutting down.
2024-12-17 00:01:16,940 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-17 00:01:16,940 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-17 00:01:19,674 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:19] "GET / HTTP/1.1" 200 -
2024-12-17 00:01:19,707 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:19] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:01:19,755 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:19] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:01:24,884 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:01:24,886 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:24] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:01:24,903 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:24] "GET /index HTTP/1.1" 200 -
2024-12-17 00:01:24,929 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:24] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:01:31,563 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:31] "POST /index HTTP/1.1" 200 -
2024-12-17 00:01:31,590 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:31] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:01:31,607 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:01:31] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:03:04,249 - INFO - main.py - Flask application is shutting down.
2024-12-17 00:03:08,637 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-17 00:03:08,637 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-17 00:03:14,579 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:14] "GET / HTTP/1.1" 200 -
2024-12-17 00:03:14,603 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:14] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:03:14,619 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:14] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:03:19,384 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:03:19,385 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:19] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:03:19,402 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:19] "GET /index HTTP/1.1" 200 -
2024-12-17 00:03:19,428 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:19] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:03:26,744 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'callsign_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 282, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 192, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'callsign_1'
2024-12-17 00:03:26,750 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:03:26] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-17 00:05:03,284 - INFO - main.py - Flask application is shutting down.
2024-12-17 00:05:07,135 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-17 00:05:07,135 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-17 00:05:13,354 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:13] "GET / HTTP/1.1" 200 -
2024-12-17 00:05:13,386 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:13] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:05:13,399 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:13] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:05:18,201 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:05:18,203 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:18] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:05:18,220 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:18] "GET /index HTTP/1.1" 200 -
2024-12-17 00:05:18,244 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:18] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:05:25,355 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:25] "POST /index HTTP/1.1" 200 -
2024-12-17 00:05:25,385 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:25] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:05:25,395 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:05:25] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:09:16,951 - INFO - main.py - Flask application is shutting down.
2024-12-17 00:09:20,030 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-17 00:09:20,031 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-17 00:09:22,860 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:22] "GET / HTTP/1.1" 200 -
2024-12-17 00:09:22,884 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:22] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:09:22,898 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:22] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:09:28,630 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:09:28,632 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:28] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:09:28,650 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:28] "GET /index HTTP/1.1" 200 -
2024-12-17 00:09:28,678 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:28] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:09:37,224 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:37] "POST /index HTTP/1.1" 200 -
2024-12-17 00:09:37,251 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:37] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:09:37,262 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:09:37] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:11:17,546 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:11:17] "POST /index HTTP/1.1" 200 -
2024-12-17 00:11:17,573 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:11:17] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:11:17,625 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:11:17] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:13:38,831 - INFO - main.py - User 'zura' logged out successfully.
2024-12-17 00:13:38,833 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:13:38] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-17 00:13:38,837 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:13:38] "GET / HTTP/1.1" 200 -
2024-12-17 00:13:38,863 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:13:38] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:13:38,897 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:13:38] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:14:06,846 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:14:06,847 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:06] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:14:06,855 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:06] "GET /index HTTP/1.1" 200 -
2024-12-17 00:14:06,885 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:06] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:14:11,854 - INFO - Insert_to_DBM.py - Using Python interpreter: E:\ZURA KOPADZE\mapping_stca\venv\Scripts\python.exe
2024-12-17 00:14:11,854 - INFO - Insert_to_DBM.py - Script path: E:\ZURA KOPADZE\mapping_stca\DBM\create_Midpoints_Table.py
2024-12-17 00:14:15,330 - INFO - Insert_to_DBM.py - Script executed successfully from path: E:\ZURA KOPADZE\mapping_stca\DBM\create_Midpoints_Table.py
Excel file loaded successfully.
Connected to the database successfully.
Results have been saved to the Midpoints database.

2024-12-17 00:14:15,906 - INFO - main.py - File 'sourse_file.xlsx' uploaded successfully.
2024-12-17 00:14:15,908 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:15] "[32mPOST /upload HTTP/1.1[0m" 302 -
2024-12-17 00:14:15,917 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:15] "GET /index HTTP/1.1" 200 -
2024-12-17 00:14:15,945 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:15] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:14:22,159 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:22] "GET / HTTP/1.1" 200 -
2024-12-17 00:14:22,175 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:22] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:14:22,214 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:22] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:14:27,774 - INFO - main.py - User 'gio' logged in successfully.
2024-12-17 00:14:27,775 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:27] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:14:27,783 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:27] "GET /index HTTP/1.1" 200 -
2024-12-17 00:14:27,817 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:27] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:14:37,050 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:37] "POST /index HTTP/1.1" 200 -
2024-12-17 00:14:37,073 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:37] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:14:37,111 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:14:37] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:18:18,999 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:18:18] "POST /index HTTP/1.1" 200 -
2024-12-17 00:18:19,023 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:18:19] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:18:19,105 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:18:19] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:19:04,545 - INFO - main.py - User 'gio' logged out successfully.
2024-12-17 00:19:04,547 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:04] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-17 00:19:04,552 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:04] "GET / HTTP/1.1" 200 -
2024-12-17 00:19:04,581 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:04] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:19:04,602 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:04] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 00:19:10,181 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 00:19:10,182 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:10] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 00:19:10,190 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:10] "GET /index HTTP/1.1" 200 -
2024-12-17 00:19:10,225 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:10] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:19:19,999 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:19] "POST /index HTTP/1.1" 200 -
2024-12-17 00:19:20,026 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:20] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:19:20,040 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:20] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 00:19:49,842 - INFO - main.py - User 'zura' logged out successfully.
2024-12-17 00:19:49,844 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:49] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-17 00:19:49,850 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:49] "GET / HTTP/1.1" 200 -
2024-12-17 00:19:49,882 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:49] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 00:19:50,172 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 00:19:50] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 08:15:14,628 - INFO - main.py - Flask application is shutting down.
2024-12-17 08:51:53,330 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-17 08:51:53,330 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-17 08:51:56,643 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:51:56] "GET / HTTP/1.1" 200 -
2024-12-17 08:51:56,669 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:51:56] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-17 08:51:56,682 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:51:56] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-17 08:52:01,782 - INFO - main.py - User 'zura' logged in successfully.
2024-12-17 08:52:01,783 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:01] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-17 08:52:01,802 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:01] "GET /index HTTP/1.1" 200 -
2024-12-17 08:52:01,831 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:01] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 08:52:09,178 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:09] "POST /index HTTP/1.1" 200 -
2024-12-17 08:52:09,206 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:09] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-17 08:52:09,216 - INFO - _internal.py - 127.0.0.1 - - [17/Dec/2024 08:52:09] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-17 09:11:24,918 - INFO - main.py - Flask application is shutting down.
2024-12-20 09:38:07,374 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 09:38:07,374 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 09:38:18,561 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:18] "GET / HTTP/1.1" 200 -
2024-12-20 09:38:18,624 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:18] "GET /static/css/Login_page.css HTTP/1.1" 200 -
2024-12-20 09:38:18,629 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-12-20 09:38:18,635 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:18] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:38:31,054 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 09:38:31,055 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:31] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 09:38:31,101 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:31] "GET /index HTTP/1.1" 200 -
2024-12-20 09:38:31,173 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:31] "GET /static/css/map_page.css HTTP/1.1" 200 -
2024-12-20 09:38:31,323 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:31] "GET /static/favicon.ico HTTP/1.1" 200 -
2024-12-20 09:38:58,415 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:58] "POST /index HTTP/1.1" 200 -
2024-12-20 09:38:58,445 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:58] "GET /static/css/map_page.css HTTP/1.1" 200 -
2024-12-20 09:38:58,445 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:38:58] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 09:42:27,940 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:27] "GET / HTTP/1.1" 200 -
2024-12-20 09:42:27,957 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:27] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:42:28,023 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:28] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:42:28,037 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-12-20 09:42:33,497 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 09:42:33,499 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:33] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 09:42:33,507 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:33] "GET /index HTTP/1.1" 200 -
2024-12-20 09:42:33,545 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:33] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:42:40,476 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:40] "POST /index HTTP/1.1" 200 -
2024-12-20 09:42:40,497 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:40] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:42:40,504 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:42:40] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 09:54:11,836 - INFO - main.py - Flask application is shutting down.
2024-12-20 09:54:20,785 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 09:54:20,785 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 09:54:22,666 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:22] "GET / HTTP/1.1" 200 -
2024-12-20 09:54:22,688 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:22] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:54:22,699 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:22] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:54:27,288 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 09:54:27,289 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:27] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 09:54:27,308 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:27] "GET /index HTTP/1.1" 200 -
2024-12-20 09:54:27,337 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:27] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:54:34,968 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 100, in index
    real_percentage, suspicious_percentage, warning_message = create_map(
NameError: name 'create_map' is not defined
2024-12-20 09:54:35,040 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:54:35] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-20 09:55:13,092 - INFO - main.py - Flask application is shutting down.
2024-12-20 09:56:00,130 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 09:56:00,130 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 09:56:02,617 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:02] "GET / HTTP/1.1" 200 -
2024-12-20 09:56:02,642 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:02] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:56:02,658 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:02] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:56:07,604 - WARNING - main.py - Failed login attempt for username: 'zura'.
2024-12-20 09:56:07,606 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:07] "POST / HTTP/1.1" 200 -
2024-12-20 09:56:07,628 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:07] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:56:07,641 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:07] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:56:12,519 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 09:56:12,520 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:12] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 09:56:12,538 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:12] "GET /index HTTP/1.1" 200 -
2024-12-20 09:56:12,559 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:12] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:56:18,350 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:18] "POST /index HTTP/1.1" 200 -
2024-12-20 09:56:18,370 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:18] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:56:18,379 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:56:18] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 09:57:16,975 - INFO - main.py - Flask application is shutting down.
2024-12-20 09:58:35,593 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 09:58:35,593 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 09:58:37,103 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:37] "GET / HTTP/1.1" 200 -
2024-12-20 09:58:37,125 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:37] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:58:37,139 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:37] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 09:58:43,488 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 09:58:43,489 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:43] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 09:58:43,508 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:43] "GET /index HTTP/1.1" 200 -
2024-12-20 09:58:43,538 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:43] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:58:55,827 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:55] "POST /index HTTP/1.1" 200 -
2024-12-20 09:58:55,852 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:55] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:58:55,857 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:58:55] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 09:59:08,963 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:59:08] "POST /index HTTP/1.1" 200 -
2024-12-20 09:59:08,988 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:59:08] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 09:59:08,996 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 09:59:08] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 10:04:45,662 - INFO - main.py - User 'zura' logged out successfully.
2024-12-20 10:04:45,663 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:04:45] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-20 10:04:45,668 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:04:45] "GET / HTTP/1.1" 200 -
2024-12-20 10:04:45,688 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:04:45] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:04:45,699 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:04:45] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 10:31:20,949 - INFO - main.py - Flask application is shutting down.
2024-12-20 10:31:29,169 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 10:31:29,169 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 10:31:29,238 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:29] "GET / HTTP/1.1" 200 -
2024-12-20 10:31:29,255 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:29] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:31:29,263 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:29] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 10:31:34,225 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 10:31:34,226 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:34] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 10:31:34,244 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:34] "GET /index HTTP/1.1" 200 -
2024-12-20 10:31:34,275 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:34] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:31:37,462 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:31:37] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:32:59,044 - INFO - main.py - Flask application is shutting down.
2024-12-20 10:59:21,644 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-20 10:59:21,671 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-20 10:59:32,970 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:32] "GET / HTTP/1.1" 200 -
2024-12-20 10:59:33,025 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:33] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:59:33,105 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:33] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-20 10:59:33,158 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-12-20 10:59:38,340 - INFO - main.py - User 'zura' logged in successfully.
2024-12-20 10:59:38,370 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:38] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-20 10:59:38,449 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:38] "GET /index HTTP/1.1" 200 -
2024-12-20 10:59:38,537 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:38] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:59:49,721 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:49] "POST /index HTTP/1.1" 200 -
2024-12-20 10:59:49,739 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:49] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:59:49,801 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:49] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 10:59:55,098 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:55] "POST /index HTTP/1.1" 200 -
2024-12-20 10:59:55,119 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:55] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:59:55,310 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:55] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 10:59:59,449 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:59] "POST /index HTTP/1.1" 200 -
2024-12-20 10:59:59,472 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:59] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 10:59:59,670 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 10:59:59] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 11:00:06,235 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:06] "POST /index HTTP/1.1" 200 -
2024-12-20 11:00:06,252 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:06] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 11:00:06,273 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:06] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 11:00:09,761 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:09] "POST /index HTTP/1.1" 200 -
2024-12-20 11:00:09,781 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:09] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 11:00:09,812 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:09] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 11:00:16,806 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:16] "POST /index HTTP/1.1" 200 -
2024-12-20 11:00:16,826 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:16] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-20 11:00:17,015 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:17] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-20 11:00:23,020 - INFO - main.py - User 'zura' logged out successfully.
2024-12-20 11:00:23,021 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:23] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-20 11:00:23,026 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:23] "GET / HTTP/1.1" 200 -
2024-12-20 11:00:23,043 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:23] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-20 11:00:23,294 - INFO - _internal.py - 127.0.0.1 - - [20/Dec/2024 11:00:23] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
