2024-11-04 14:37:08,203 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 14:37:08,203 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 14:37:08,205 - INFO -  * Restarting with stat
2024-11-04 14:37:09,884 - WARNING -  * Debugger is active!
2024-11-04 14:37:09,890 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:37:52,454 - INFO - 127.0.0.1 - - [04/Nov/2024 14:37:52] "GET / HTTP/1.1" 200 -
2024-11-04 14:37:52,523 - INFO - 127.0.0.1 - - [04/Nov/2024 14:37:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 14:37:58,357 - INFO - 127.0.0.1 - - [04/Nov/2024 14:37:58] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 14:37:58,379 - INFO - 127.0.0.1 - - [04/Nov/2024 14:37:58] "GET /index HTTP/1.1" 200 -
2024-11-04 14:38:06,475 - INFO - Data range selected: 2024-01-04 to 2024-12-29 with filter: both
2024-11-04 14:38:07,517 - INFO - 127.0.0.1 - - [04/Nov/2024 14:38:07] "POST /index HTTP/1.1" 200 -
2024-11-04 14:38:07,542 - INFO - 127.0.0.1 - - [04/Nov/2024 14:38:07] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 14:39:23,093 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 14:39:23,093 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 14:39:23,094 - INFO -  * Restarting with stat
2024-11-04 14:39:24,734 - WARNING -  * Debugger is active!
2024-11-04 14:39:24,741 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:41:14,935 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:41:15,087 - INFO -  * Restarting with stat
2024-11-04 14:41:15,188 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:41:15,321 - INFO -  * Restarting with stat
2024-11-04 14:41:17,274 - WARNING -  * Debugger is active!
2024-11-04 14:41:17,274 - WARNING -  * Debugger is active!
2024-11-04 14:41:17,281 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:41:17,281 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:41:59,451 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:41:59,481 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:41:59,572 - INFO -  * Restarting with stat
2024-11-04 14:41:59,605 - INFO -  * Restarting with stat
2024-11-04 14:42:01,631 - WARNING -  * Debugger is active!
2024-11-04 14:42:01,639 - WARNING -  * Debugger is active!
2024-11-04 14:42:01,641 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:42:01,647 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:42:35,842 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:42:35,873 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 14:42:36,019 - INFO -  * Restarting with stat
2024-11-04 14:42:36,053 - INFO -  * Restarting with stat
2024-11-04 14:42:38,171 - WARNING -  * Debugger is active!
2024-11-04 14:42:38,171 - WARNING -  * Debugger is active!
2024-11-04 14:42:38,179 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:43:16,210 - INFO - Flask application is shutting down.
2024-11-04 14:43:16,251 - INFO - Flask application is shutting down.
2024-11-04 14:43:16,359 - INFO - Flask application is shutting down.
2024-11-04 14:43:16,393 - INFO - Flask application is shutting down.
2024-11-04 14:43:47,809 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 14:43:47,810 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 14:43:47,811 - INFO -  * Restarting with stat
2024-11-04 14:43:49,506 - WARNING -  * Debugger is active!
2024-11-04 14:43:49,513 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:43:53,727 - INFO - 127.0.0.1 - - [04/Nov/2024 14:43:53] "[31m[1mGET /index HTTP/1.1[0m" 401 -
2024-11-04 14:43:59,148 - INFO - 127.0.0.1 - - [04/Nov/2024 14:43:59] "GET / HTTP/1.1" 200 -
2024-11-04 14:44:04,338 - INFO - User 'zura' logged in successfully.
2024-11-04 14:44:04,339 - INFO - 127.0.0.1 - - [04/Nov/2024 14:44:04] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 14:44:04,358 - INFO - 127.0.0.1 - - [04/Nov/2024 14:44:04] "GET /index HTTP/1.1" 200 -
2024-11-04 14:44:04,428 - INFO - 127.0.0.1 - - [04/Nov/2024 14:44:04] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 14:44:15,580 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 14:44:16,633 - INFO - 127.0.0.1 - - [04/Nov/2024 14:44:16] "POST /index HTTP/1.1" 200 -
2024-11-04 14:44:16,668 - INFO - 127.0.0.1 - - [04/Nov/2024 14:44:16] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 14:50:59,518 - INFO - 127.0.0.1 - - [04/Nov/2024 14:50:59] "GET / HTTP/1.1" 200 -
2024-11-04 14:51:03,912 - WARNING - Failed login attempt for username: 'gio'.
2024-11-04 14:51:03,914 - INFO - 127.0.0.1 - - [04/Nov/2024 14:51:03] "POST / HTTP/1.1" 200 -
2024-11-04 14:51:09,873 - WARNING - Failed login attempt for username: 'gio'.
2024-11-04 14:51:09,875 - INFO - 127.0.0.1 - - [04/Nov/2024 14:51:09] "POST / HTTP/1.1" 200 -
2024-11-04 14:51:18,544 - WARNING - Failed login attempt for username: 'gio'.
2024-11-04 14:51:18,547 - INFO - 127.0.0.1 - - [04/Nov/2024 14:51:18] "POST / HTTP/1.1" 200 -
2024-11-04 14:51:22,246 - INFO - Flask application is shutting down.
2024-11-04 14:51:22,373 - INFO - Flask application is shutting down.
2024-11-04 14:51:31,644 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 14:51:31,644 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 14:51:31,646 - INFO -  * Restarting with stat
2024-11-04 14:51:33,457 - WARNING -  * Debugger is active!
2024-11-04 14:51:33,463 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 14:51:48,367 - WARNING - Failed login attempt for username: 'gio'.
2024-11-04 14:51:48,371 - INFO - 127.0.0.1 - - [04/Nov/2024 14:51:48] "POST / HTTP/1.1" 200 -
2024-11-04 14:55:13,137 - WARNING - Failed login attempt for username: 'gio'.
2024-11-04 14:55:13,139 - INFO - 127.0.0.1 - - [04/Nov/2024 14:55:13] "POST / HTTP/1.1" 200 -
2024-11-04 15:02:37,140 - INFO - Flask application is shutting down.
2024-11-04 15:02:37,251 - INFO - Flask application is shutting down.
2024-11-04 15:02:40,868 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 15:02:40,869 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 15:02:40,870 - INFO -  * Restarting with stat
2024-11-04 15:02:42,526 - WARNING -  * Debugger is active!
2024-11-04 15:02:42,534 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 15:02:56,396 - INFO - 127.0.0.1 - - [04/Nov/2024 15:02:56] "GET / HTTP/1.1" 200 -
2024-11-04 15:03:02,274 - INFO - User 'gio' logged in successfully.
2024-11-04 15:03:02,276 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:02] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 15:03:02,297 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:02] "GET /index HTTP/1.1" 200 -
2024-11-04 15:03:12,825 - INFO - Data range selected: 2024-02-10 to 2024-11-04 with filter: both
2024-11-04 15:03:13,873 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:13] "POST /index HTTP/1.1" 200 -
2024-11-04 15:03:13,903 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:13] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 15:03:26,220 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:26] "GET / HTTP/1.1" 200 -
2024-11-04 15:03:29,873 - WARNING - Failed login attempt for username: 'aegfre'.
2024-11-04 15:03:29,875 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:29] "POST / HTTP/1.1" 200 -
2024-11-04 15:03:36,975 - INFO - User 'zura' logged in successfully.
2024-11-04 15:03:36,977 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:36] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 15:03:36,988 - INFO - 127.0.0.1 - - [04/Nov/2024 15:03:36] "GET /index HTTP/1.1" 200 -
2024-11-04 15:04:11,460 - INFO - Flask application is shutting down.
2024-11-04 15:04:11,594 - INFO - Flask application is shutting down.
2024-11-04 15:12:47,516 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 15:12:47,516 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 15:12:47,517 - INFO -  * Restarting with stat
2024-11-04 15:12:49,424 - WARNING -  * Debugger is active!
2024-11-04 15:12:49,431 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 15:12:51,222 - INFO - 127.0.0.1 - - [04/Nov/2024 15:12:51] "GET / HTTP/1.1" 200 -
2024-11-04 15:12:56,875 - INFO - User 'zura' logged in successfully.
2024-11-04 15:12:56,876 - INFO - 127.0.0.1 - - [04/Nov/2024 15:12:56] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 15:12:56,897 - INFO - 127.0.0.1 - - [04/Nov/2024 15:12:56] "GET /index HTTP/1.1" 200 -
2024-11-04 15:13:05,432 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 15:13:06,447 - INFO - 127.0.0.1 - - [04/Nov/2024 15:13:06] "POST /index HTTP/1.1" 200 -
2024-11-04 15:13:06,472 - INFO - 127.0.0.1 - - [04/Nov/2024 15:13:06] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 16:02:46,111 - INFO - 127.0.0.1 - - [04/Nov/2024 16:02:46] "GET / HTTP/1.1" 200 -
2024-11-04 16:02:58,295 - INFO - User 'gio' logged in successfully.
2024-11-04 16:02:58,297 - INFO - 127.0.0.1 - - [04/Nov/2024 16:02:58] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:02:58,305 - INFO - 127.0.0.1 - - [04/Nov/2024 16:02:58] "GET /index HTTP/1.1" 200 -
2024-11-04 16:03:08,068 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 16:03:09,098 - INFO - 127.0.0.1 - - [04/Nov/2024 16:03:09] "POST /index HTTP/1.1" 200 -
2024-11-04 16:03:09,124 - INFO - 127.0.0.1 - - [04/Nov/2024 16:03:09] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 16:03:57,527 - INFO - 127.0.0.1 - - [04/Nov/2024 16:03:57] "GET / HTTP/1.1" 200 -
2024-11-04 16:04:06,508 - INFO - User 'zura' logged in successfully.
2024-11-04 16:04:06,510 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:06] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:04:06,517 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:06] "GET /index HTTP/1.1" 200 -
2024-11-04 16:04:13,981 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:04:15,047 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:15] "POST /index HTTP/1.1" 200 -
2024-11-04 16:04:15,073 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:15] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 16:04:29,288 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:29] "GET / HTTP/1.1" 200 -
2024-11-04 16:04:34,540 - WARNING - Failed login attempt for username: 'hjgf'.
2024-11-04 16:04:34,543 - INFO - 127.0.0.1 - - [04/Nov/2024 16:04:34] "POST / HTTP/1.1" 200 -
2024-11-04 16:05:23,736 - INFO - User 'zura' logged in successfully.
2024-11-04 16:05:23,737 - INFO - 127.0.0.1 - - [04/Nov/2024 16:05:23] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:05:23,744 - INFO - 127.0.0.1 - - [04/Nov/2024 16:05:23] "GET /index HTTP/1.1" 200 -
2024-11-04 16:08:43,318 - INFO - Flask application is shutting down.
2024-11-04 16:08:43,459 - INFO - Flask application is shutting down.
2024-11-04 16:08:45,697 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:08:45,697 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:08:45,699 - INFO -  * Restarting with stat
2024-11-04 16:08:47,544 - WARNING -  * Debugger is active!
2024-11-04 16:08:47,551 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:08:50,264 - INFO - 127.0.0.1 - - [04/Nov/2024 16:08:50] "GET / HTTP/1.1" 200 -
2024-11-04 16:08:56,259 - INFO - User 'zura' logged in successfully.
2024-11-04 16:08:56,261 - INFO - 127.0.0.1 - - [04/Nov/2024 16:08:56] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:08:56,283 - INFO - 127.0.0.1 - - [04/Nov/2024 16:08:56] "GET /index HTTP/1.1" 200 -
2024-11-04 16:09:06,828 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:09:06,837 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:06] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:09:06,876 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:09:06,877 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:09:06,913 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:09:06,926 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:09:13,685 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 16:09:13,916 - INFO -  * Restarting with stat
2024-11-04 16:09:14,947 - INFO - Flask application is shutting down.
2024-11-04 16:09:17,808 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:09:17,808 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:09:17,809 - INFO -  * Restarting with stat
2024-11-04 16:09:19,528 - WARNING -  * Debugger is active!
2024-11-04 16:09:19,535 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:09:23,634 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:23] "[31m[1mGET /index HTTP/1.1[0m" 401 -
2024-11-04 16:09:26,837 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:26] "GET / HTTP/1.1" 200 -
2024-11-04 16:09:32,785 - INFO - User 'zura' logged in successfully.
2024-11-04 16:09:32,786 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:09:32,804 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:32] "GET /index HTTP/1.1" 200 -
2024-11-04 16:09:32,856 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:32] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:09:42,525 - INFO - Data range selected: 2024-01-31 to 2024-11-04 with filter: both
2024-11-04 16:09:42,536 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:42] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:09:42,559 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:09:42,560 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:09:42,567 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:09:42,578 - INFO - 127.0.0.1 - - [04/Nov/2024 16:09:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:02,140 - INFO - Data range selected: 2024-01-31 to 2024-11-04 with filter: both
2024-11-04 16:10:02,143 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:02] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:10:02,162 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:02] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:10:02,164 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:02] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:10:02,174 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:02] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:02,182 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:02] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:05,022 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:05] "GET /index HTTP/1.1" 200 -
2024-11-04 16:10:05,083 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:05] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:10:11,997 - INFO - Data range selected: 2024-11-15 to 2024-11-04 with filter: both
2024-11-04 16:10:12,001 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:12] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:10:12,022 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:12] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:10:12,023 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:12] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:10:12,038 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:12] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:12,047 - INFO - 127.0.0.1 - - [04/Nov/2024 16:10:12] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:17,428 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:17] "GET / HTTP/1.1" 200 -
2024-11-04 16:10:17,523 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 16:10:23,472 - INFO - User 'zura' logged in successfully.
2024-11-04 16:10:23,474 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:23] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:10:23,481 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:23] "GET /index HTTP/1.1" 200 -
2024-11-04 16:10:30,111 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:10:30,116 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:30] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:10:30,131 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:30] "GET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2024-11-04 16:10:30,132 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:30] "GET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2024-11-04 16:10:30,145 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:30] "GET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2024-11-04 16:10:30,176 - INFO - 172.16.12.13 - - [04/Nov/2024 16:10:30] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:10:45,215 - INFO - Flask application is shutting down.
2024-11-04 16:10:45,333 - INFO - Flask application is shutting down.
2024-11-04 16:11:29,599 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:11:29,599 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:11:29,600 - INFO -  * Restarting with stat
2024-11-04 16:11:31,695 - WARNING -  * Debugger is active!
2024-11-04 16:11:31,702 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:11:34,877 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:34] "GET / HTTP/1.1" 200 -
2024-11-04 16:11:38,417 - WARNING - Failed login attempt for username: 'dsgf'.
2024-11-04 16:11:38,419 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:38] "POST / HTTP/1.1" 200 -
2024-11-04 16:11:44,194 - INFO - User 'zura' logged in successfully.
2024-11-04 16:11:44,195 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:44] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:11:44,213 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:44] "GET /index HTTP/1.1" 200 -
2024-11-04 16:11:44,295 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:44] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:11:51,850 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:11:51,861 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:51] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:11:51,884 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:51] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:11:51,885 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:51] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:11:51,893 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:51] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:11:51,927 - INFO - 127.0.0.1 - - [04/Nov/2024 16:11:51] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:27:24,329 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:27:24,329 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:27:24,332 - INFO -  * Restarting with stat
2024-11-04 16:27:26,264 - WARNING -  * Debugger is active!
2024-11-04 16:27:26,321 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:27:28,547 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:28] "GET / HTTP/1.1" 200 -
2024-11-04 16:27:28,842 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 16:27:37,662 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:37] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:27:37,728 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:37] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2024-11-04 16:27:37,731 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:37] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2024-11-04 16:27:38,093 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:38] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2024-11-04 16:27:38,144 - INFO - 172.16.12.13 - - [04/Nov/2024 16:27:38] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:27:55,988 - INFO - Flask application is shutting down.
2024-11-04 16:27:56,142 - INFO - Flask application is shutting down.
2024-11-04 16:27:59,273 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:27:59,274 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:27:59,275 - INFO -  * Restarting with stat
2024-11-04 16:28:00,969 - WARNING -  * Debugger is active!
2024-11-04 16:28:00,975 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:28:25,267 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:25] "GET / HTTP/1.1" 200 -
2024-11-04 16:28:25,670 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:25] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 16:28:30,714 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:30] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:28:30,849 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:30] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:28:30,851 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:30] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:28:30,998 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:30] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:31,052 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:31] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:42,981 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:42] "GET / HTTP/1.1" 200 -
2024-11-04 16:28:49,340 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:49] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:28:49,355 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:49] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:28:49,356 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:49] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:28:49,370 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:49] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:49,389 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:49] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:53,835 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:53] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:28:53,854 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:53] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:28:53,856 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:53] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:28:53,865 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:53] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:53,886 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:53] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:55,634 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:55] "GET / HTTP/1.1" 200 -
2024-11-04 16:28:59,105 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:59] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:28:59,124 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:59] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:28:59,126 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:59] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:28:59,136 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:59] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:28:59,158 - INFO - 127.0.0.1 - - [04/Nov/2024 16:28:59] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:29:46,901 - INFO - Flask application is shutting down.
2024-11-04 16:29:47,015 - INFO - Flask application is shutting down.
2024-11-04 16:29:57,842 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:29:57,842 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:29:57,843 - INFO -  * Restarting with stat
2024-11-04 16:29:59,571 - WARNING -  * Debugger is active!
2024-11-04 16:29:59,578 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:30:00,823 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:00] "GET / HTTP/1.1" 200 -
2024-11-04 16:30:06,140 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:06] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 16:30:06,165 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:06] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:30:06,167 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:06] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:30:06,176 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:06] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:30:06,195 - INFO - 127.0.0.1 - - [04/Nov/2024 16:30:06] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:31:43,207 - INFO - Flask application is shutting down.
2024-11-04 16:31:43,335 - INFO - Flask application is shutting down.
2024-11-04 16:31:46,821 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:31:46,821 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:31:46,822 - INFO -  * Restarting with stat
2024-11-04 16:31:48,591 - WARNING -  * Debugger is active!
2024-11-04 16:31:48,598 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:31:50,660 - INFO - 127.0.0.1 - - [04/Nov/2024 16:31:50] "GET / HTTP/1.1" 200 -
2024-11-04 16:31:56,208 - INFO - User 'zura' logged in successfully.
2024-11-04 16:31:56,210 - INFO - 127.0.0.1 - - [04/Nov/2024 16:31:56] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:31:56,254 - INFO - 127.0.0.1 - - [04/Nov/2024 16:31:56] "GET /index HTTP/1.1" 200 -
2024-11-04 16:31:56,440 - INFO - 127.0.0.1 - - [04/Nov/2024 16:31:56] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:32:07,065 - INFO - Data range selected: 2024-01-04 to 2024-01-21 with filter: both
2024-11-04 16:32:07,225 - INFO - 127.0.0.1 - - [04/Nov/2024 16:32:07] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:32:07,266 - INFO - 127.0.0.1 - - [04/Nov/2024 16:32:07] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:32:07,290 - INFO - 127.0.0.1 - - [04/Nov/2024 16:32:07] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:32:07,311 - INFO - 127.0.0.1 - - [04/Nov/2024 16:32:07] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:32:07,320 - INFO - 127.0.0.1 - - [04/Nov/2024 16:32:07] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:34:02,459 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 16:34:02,596 - INFO -  * Restarting with stat
2024-11-04 16:34:04,380 - WARNING -  * Debugger is active!
2024-11-04 16:34:04,386 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:36:28,780 - INFO - Flask application is shutting down.
2024-11-04 16:36:28,891 - INFO - Flask application is shutting down.
2024-11-04 16:36:35,948 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:36:35,948 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:36:35,950 - INFO -  * Restarting with stat
2024-11-04 16:36:37,661 - WARNING -  * Debugger is active!
2024-11-04 16:36:37,668 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:36:47,094 - INFO - 127.0.0.1 - - [04/Nov/2024 16:36:47] "GET / HTTP/1.1" 200 -
2024-11-04 16:36:52,215 - INFO - User 'zura' logged in successfully.
2024-11-04 16:36:52,216 - INFO - 127.0.0.1 - - [04/Nov/2024 16:36:52] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:36:52,239 - INFO - 127.0.0.1 - - [04/Nov/2024 16:36:52] "GET /index HTTP/1.1" 200 -
2024-11-04 16:36:52,302 - INFO - 127.0.0.1 - - [04/Nov/2024 16:36:52] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:37:00,943 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:37:00,953 - INFO - 127.0.0.1 - - [04/Nov/2024 16:37:00] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:37:00,970 - INFO - 127.0.0.1 - - [04/Nov/2024 16:37:00] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:37:00,971 - INFO - 127.0.0.1 - - [04/Nov/2024 16:37:00] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:37:00,991 - INFO - 127.0.0.1 - - [04/Nov/2024 16:37:00] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:37:01,000 - INFO - 127.0.0.1 - - [04/Nov/2024 16:37:01] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:40:22,643 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\DBM\\Connect_to_DBM.py', reloading
2024-11-04 16:40:22,788 - INFO -  * Restarting with stat
2024-11-04 16:40:24,609 - WARNING -  * Debugger is active!
2024-11-04 16:40:24,616 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:40:39,660 - INFO - Flask application is shutting down.
2024-11-04 16:40:39,784 - INFO - Flask application is shutting down.
2024-11-04 16:40:41,889 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:40:41,889 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:40:41,891 - INFO -  * Restarting with stat
2024-11-04 16:40:43,712 - WARNING -  * Debugger is active!
2024-11-04 16:40:43,719 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:40:50,092 - INFO - 127.0.0.1 - - [04/Nov/2024 16:40:50] "GET / HTTP/1.1" 200 -
2024-11-04 16:40:56,226 - INFO - User 'zura' logged in successfully.
2024-11-04 16:40:56,227 - INFO - 127.0.0.1 - - [04/Nov/2024 16:40:56] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:40:56,247 - INFO - 127.0.0.1 - - [04/Nov/2024 16:40:56] "GET /index HTTP/1.1" 200 -
2024-11-04 16:40:56,323 - INFO - 127.0.0.1 - - [04/Nov/2024 16:40:56] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:41:03,231 - INFO - Data range selected: 2024-01-04 to 2024-11-13 with filter: both
2024-11-04 16:41:03,241 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:03] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:41:03,259 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:03] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:41:03,261 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:03] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:41:03,275 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:03] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:41:03,286 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:03] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:41:19,597 - INFO - Flask application is shutting down.
2024-11-04 16:41:19,710 - INFO - Flask application is shutting down.
2024-11-04 16:41:32,964 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:41:32,964 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:41:32,964 - INFO -  * Restarting with stat
2024-11-04 16:41:35,816 - WARNING -  * Debugger is active!
2024-11-04 16:41:35,831 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:41:38,500 - INFO - Flask application is shutting down.
2024-11-04 16:41:38,646 - INFO - Flask application is shutting down.
2024-11-04 16:41:40,887 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:41:40,887 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:41:40,888 - INFO -  * Restarting with stat
2024-11-04 16:41:42,545 - WARNING -  * Debugger is active!
2024-11-04 16:41:42,552 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:41:50,475 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:50] "[31m[1mGET /index HTTP/1.1[0m" 401 -
2024-11-04 16:41:54,211 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:54] "GET / HTTP/1.1" 200 -
2024-11-04 16:41:59,306 - INFO - User 'zura' logged in successfully.
2024-11-04 16:41:59,307 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:59] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:41:59,329 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:59] "GET /index HTTP/1.1" 200 -
2024-11-04 16:41:59,406 - INFO - 127.0.0.1 - - [04/Nov/2024 16:41:59] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:42:06,735 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 16:42:06,745 - INFO - 127.0.0.1 - - [04/Nov/2024 16:42:06] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:42:06,764 - INFO - 127.0.0.1 - - [04/Nov/2024 16:42:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:42:06,767 - INFO - 127.0.0.1 - - [04/Nov/2024 16:42:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:42:06,779 - INFO - 127.0.0.1 - - [04/Nov/2024 16:42:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:42:06,790 - INFO - 127.0.0.1 - - [04/Nov/2024 16:42:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:44:52,451 - INFO - Flask application is shutting down.
2024-11-04 16:44:52,568 - INFO - Flask application is shutting down.
2024-11-04 16:44:54,725 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:44:54,725 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:44:54,727 - INFO -  * Restarting with stat
2024-11-04 16:44:56,406 - WARNING -  * Debugger is active!
2024-11-04 16:44:56,413 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:45:02,214 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:02] "GET / HTTP/1.1" 200 -
2024-11-04 16:45:08,908 - INFO - User 'zura' logged in successfully.
2024-11-04 16:45:08,909 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:08] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:45:08,929 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:08] "GET /index HTTP/1.1" 200 -
2024-11-04 16:45:08,989 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:08] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:45:16,599 - INFO - Data range selected: 2024-01-04 to 2024-08-04 with filter: both
2024-11-04 16:45:16,610 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:16] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:45:16,627 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:16] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:45:16,632 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:16] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:45:16,644 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:16] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:45:16,652 - INFO - 127.0.0.1 - - [04/Nov/2024 16:45:16] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:47:09,892 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 16:47:10,011 - INFO -  * Restarting with stat
2024-11-04 16:47:11,744 - WARNING -  * Debugger is active!
2024-11-04 16:47:11,750 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:50:13,829 - INFO - Flask application is shutting down.
2024-11-04 16:50:13,943 - INFO - Flask application is shutting down.
2024-11-04 16:50:17,239 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:50:17,239 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:50:17,240 - INFO -  * Restarting with stat
2024-11-04 16:50:19,029 - WARNING -  * Debugger is active!
2024-11-04 16:50:19,039 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:50:23,410 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:23] "GET / HTTP/1.1" 200 -
2024-11-04 16:50:29,197 - INFO - User 'zura' logged in successfully.
2024-11-04 16:50:29,198 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:29] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:50:29,218 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:29] "GET /index HTTP/1.1" 200 -
2024-11-04 16:50:29,282 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:29] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:50:37,225 - INFO - Data range selected: 2024-11-01 to 2024-12-28 with filter: both
2024-11-04 16:50:37,235 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:37] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:50:37,256 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:37] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:50:37,257 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:37] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:50:37,263 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:37] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:50:37,276 - INFO - 127.0.0.1 - - [04/Nov/2024 16:50:37] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:51:41,232 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 16:51:41,407 - INFO -  * Restarting with stat
2024-11-04 16:51:43,370 - WARNING -  * Debugger is active!
2024-11-04 16:51:43,377 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:52:18,169 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 16:52:18,282 - INFO -  * Restarting with stat
2024-11-04 16:54:36,656 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:54:36,656 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:54:36,658 - INFO -  * Restarting with stat
2024-11-04 16:54:38,335 - WARNING -  * Debugger is active!
2024-11-04 16:54:38,342 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:54:44,042 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:44] "GET / HTTP/1.1" 200 -
2024-11-04 16:54:50,315 - INFO - User 'zura' logged in successfully.
2024-11-04 16:54:50,316 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:50] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:54:50,336 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:50] "GET /index HTTP/1.1" 200 -
2024-11-04 16:54:50,401 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:50] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:54:54,878 - INFO - Data range selected: 2024-11-06 to 2024-11-07 with filter: both
2024-11-04 16:54:54,889 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:54] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:54:54,910 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:54] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:54:54,910 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:54] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:54:54,922 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:54] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:54:54,932 - INFO - 127.0.0.1 - - [04/Nov/2024 16:54:54] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:56:15,677 - INFO - Flask application is shutting down.
2024-11-04 16:56:15,790 - INFO - Flask application is shutting down.
2024-11-04 16:56:18,892 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:56:18,892 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:56:18,893 - INFO -  * Restarting with stat
2024-11-04 16:56:20,626 - WARNING -  * Debugger is active!
2024-11-04 16:56:20,632 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:56:25,123 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:25] "GET / HTTP/1.1" 200 -
2024-11-04 16:56:38,264 - INFO - User 'zura' logged in successfully.
2024-11-04 16:56:38,265 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:38] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:56:38,283 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:38] "GET /index HTTP/1.1" 200 -
2024-11-04 16:56:39,956 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:39] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:56:48,012 - INFO - Data range selected: 2024-11-01 to 2024-11-30 with filter: both
2024-11-04 16:56:48,023 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:48] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:56:48,044 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:48] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:56:48,046 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:48] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:56:48,060 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:48] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:56:48,068 - INFO - 127.0.0.1 - - [04/Nov/2024 16:56:48] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:56:56,853 - INFO - Flask application is shutting down.
2024-11-04 16:56:56,967 - INFO - Flask application is shutting down.
2024-11-04 16:57:00,594 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:57:00,594 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:57:00,595 - INFO -  * Restarting with stat
2024-11-04 16:57:02,242 - WARNING -  * Debugger is active!
2024-11-04 16:57:02,248 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:57:22,143 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:22] "[31m[1mPOST /index HTTP/1.1[0m" 401 -
2024-11-04 16:57:25,721 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:25] "GET / HTTP/1.1" 200 -
2024-11-04 16:57:32,060 - INFO - User 'zura' logged in successfully.
2024-11-04 16:57:32,061 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:57:32,080 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:32] "GET /index HTTP/1.1" 200 -
2024-11-04 16:57:32,120 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:32] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:57:39,143 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 16:57:39,152 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:39] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:57:39,172 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:57:39,173 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:57:39,186 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:57:39,195 - INFO - 127.0.0.1 - - [04/Nov/2024 16:57:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:59:18,473 - INFO - Flask application is shutting down.
2024-11-04 16:59:18,600 - INFO - Flask application is shutting down.
2024-11-04 16:59:20,681 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 16:59:20,681 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 16:59:20,683 - INFO -  * Restarting with stat
2024-11-04 16:59:22,414 - WARNING -  * Debugger is active!
2024-11-04 16:59:22,423 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 16:59:25,892 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:25] "GET / HTTP/1.1" 200 -
2024-11-04 16:59:32,400 - INFO - User 'zura' logged in successfully.
2024-11-04 16:59:32,401 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 16:59:32,424 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:32] "GET /index HTTP/1.1" 200 -
2024-11-04 16:59:32,512 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:32] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 16:59:39,022 - INFO - Data range selected: 2024-05-04 to 2024-11-04 with filter: both
2024-11-04 16:59:39,032 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:39] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 16:59:39,050 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 16:59:39,052 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 16:59:39,062 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 16:59:39,070 - INFO - 127.0.0.1 - - [04/Nov/2024 16:59:39] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:02:52,369 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\create_map.py', reloading
2024-11-04 17:02:52,516 - INFO -  * Restarting with stat
2024-11-04 17:02:54,256 - WARNING -  * Debugger is active!
2024-11-04 17:02:54,263 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:04:42,348 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\create_map.py', reloading
2024-11-04 17:04:42,513 - INFO -  * Restarting with stat
2024-11-04 17:04:44,532 - WARNING -  * Debugger is active!
2024-11-04 17:04:44,539 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:08:26,664 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\DBM\\Connect_to_DBM.py', reloading
2024-11-04 17:08:26,791 - INFO -  * Restarting with stat
2024-11-04 17:08:29,146 - WARNING -  * Debugger is active!
2024-11-04 17:08:29,153 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:09:28,842 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\create_map.py', reloading
2024-11-04 17:09:28,994 - INFO -  * Restarting with stat
2024-11-04 17:09:30,921 - WARNING -  * Debugger is active!
2024-11-04 17:09:30,927 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:10:24,675 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\DBM\\Connect_to_DBM.py', reloading
2024-11-04 17:10:24,881 - INFO -  * Restarting with stat
2024-11-04 17:20:02,268 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:20:02,268 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:20:02,270 - INFO -  * Restarting with stat
2024-11-04 17:20:03,958 - WARNING -  * Debugger is active!
2024-11-04 17:20:03,964 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:20:07,601 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:07] "GET / HTTP/1.1" 200 -
2024-11-04 17:20:13,778 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:13] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 17:20:13,827 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:13] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:20:13,829 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:13] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:20:13,850 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:13] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:20:13,867 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:13] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:20:25,283 - INFO - Flask application is shutting down.
2024-11-04 17:20:25,397 - INFO - Flask application is shutting down.
2024-11-04 17:20:28,362 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:20:28,362 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:20:28,363 - INFO -  * Restarting with stat
2024-11-04 17:20:30,085 - WARNING -  * Debugger is active!
2024-11-04 17:20:30,092 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:20:31,304 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:31] "GET / HTTP/1.1" 200 -
2024-11-04 17:20:36,104 - INFO - User 'zura' logged in successfully.
2024-11-04 17:20:36,106 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:36] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 17:20:36,128 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:36] "GET /index HTTP/1.1" 200 -
2024-11-04 17:20:36,281 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:36] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 17:20:43,166 - INFO - Data range selected: 2024-01-04 to 2024-11-14 with filter: both
2024-11-04 17:20:43,176 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:43] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 17:20:43,193 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:43] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:20:43,194 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:43] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:20:43,209 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:43] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:20:43,220 - INFO - 127.0.0.1 - - [04/Nov/2024 17:20:43] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:22:50,316 - INFO - Flask application is shutting down.
2024-11-04 17:22:50,429 - INFO - Flask application is shutting down.
2024-11-04 17:22:54,124 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:22:54,124 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:22:54,126 - INFO -  * Restarting with stat
2024-11-04 17:22:55,809 - WARNING -  * Debugger is active!
2024-11-04 17:22:55,815 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:24:36,000 - INFO - Flask application is shutting down.
2024-11-04 17:24:36,115 - INFO - Flask application is shutting down.
2024-11-04 17:24:38,226 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:24:38,226 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:24:38,228 - INFO -  * Restarting with stat
2024-11-04 17:24:39,886 - WARNING -  * Debugger is active!
2024-11-04 17:24:39,893 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:24:49,338 - INFO - 127.0.0.1 - - [04/Nov/2024 17:24:49] "GET / HTTP/1.1" 200 -
2024-11-04 17:24:53,117 - WARNING - Failed login attempt for username: 'd'.
2024-11-04 17:24:53,119 - INFO - 127.0.0.1 - - [04/Nov/2024 17:24:53] "POST / HTTP/1.1" 200 -
2024-11-04 17:24:57,984 - INFO - User 'zura' logged in successfully.
2024-11-04 17:24:57,985 - INFO - 127.0.0.1 - - [04/Nov/2024 17:24:57] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 17:24:58,004 - INFO - 127.0.0.1 - - [04/Nov/2024 17:24:58] "GET /index HTTP/1.1" 200 -
2024-11-04 17:24:58,053 - INFO - 127.0.0.1 - - [04/Nov/2024 17:24:58] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 17:25:06,006 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 17:25:06,018 - INFO - 127.0.0.1 - - [04/Nov/2024 17:25:06] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 17:25:06,036 - INFO - 127.0.0.1 - - [04/Nov/2024 17:25:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:25:06,037 - INFO - 127.0.0.1 - - [04/Nov/2024 17:25:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:25:06,045 - INFO - 127.0.0.1 - - [04/Nov/2024 17:25:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:25:06,059 - INFO - 127.0.0.1 - - [04/Nov/2024 17:25:06] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:25:20,328 - INFO - Flask application is shutting down.
2024-11-04 17:25:20,447 - INFO - Flask application is shutting down.
2024-11-04 17:25:22,555 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:25:22,555 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:25:22,556 - INFO -  * Restarting with stat
2024-11-04 17:25:24,416 - WARNING -  * Debugger is active!
2024-11-04 17:25:24,422 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:26:17,418 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\DBM\\Connect_to_DBM.py', reloading
2024-11-04 17:26:17,533 - INFO -  * Restarting with stat
2024-11-04 17:53:25,756 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:53:25,756 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:53:25,757 - INFO -  * Restarting with stat
2024-11-04 17:53:27,461 - WARNING -  * Debugger is active!
2024-11-04 17:53:27,467 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:53:32,905 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:32] "GET / HTTP/1.1" 200 -
2024-11-04 17:53:39,708 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:39] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2024-11-04 17:53:39,741 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:39] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:53:39,742 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:39] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:53:39,761 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:53:39,777 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:39] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:53:51,348 - INFO - Flask application is shutting down.
2024-11-04 17:53:51,461 - INFO - Flask application is shutting down.
2024-11-04 17:53:54,528 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 17:53:54,529 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 17:53:54,530 - INFO -  * Restarting with stat
2024-11-04 17:53:56,270 - WARNING -  * Debugger is active!
2024-11-04 17:53:56,276 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 17:53:57,208 - INFO - 127.0.0.1 - - [04/Nov/2024 17:53:57] "GET / HTTP/1.1" 200 -
2024-11-04 17:54:03,436 - INFO - User 'zura' logged in successfully.
2024-11-04 17:54:03,438 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:03] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 17:54:03,459 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:03] "GET /index HTTP/1.1" 200 -
2024-11-04 17:54:03,543 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:03] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 17:54:11,292 - INFO - Data range selected: 2024-01-26 to 2024-12-04 with filter: both
2024-11-04 17:54:11,302 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:11] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 17:54:11,322 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:11] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:54:11,323 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:11] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:54:11,337 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:11] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:54:11,351 - INFO - 127.0.0.1 - - [04/Nov/2024 17:54:11] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:57:29,677 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:29] "GET / HTTP/1.1" 200 -
2024-11-04 17:57:35,419 - INFO - User 'zura' logged in successfully.
2024-11-04 17:57:35,420 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:35] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 17:57:35,428 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:35] "GET /index HTTP/1.1" 200 -
2024-11-04 17:57:35,476 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:35] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 17:57:42,909 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 17:57:42,914 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:42] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 17:57:42,917 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 17:57:42,932 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:57:42,933 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:57:42,949 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:57:42,959 - INFO - 127.0.0.1 - - [04/Nov/2024 17:57:42] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:59:22,518 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:22] "GET / HTTP/1.1" 200 -
2024-11-04 17:59:22,707 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 17:59:29,943 - INFO - User 'zura' logged in successfully.
2024-11-04 17:59:29,945 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:29] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 17:59:29,952 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:29] "GET /index HTTP/1.1" 200 -
2024-11-04 17:59:41,502 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:41] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 17:59:49,999 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 17:59:50,004 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:50] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 17:59:50,005 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 17:59:50,025 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:50] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 17:59:50,026 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:50] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 17:59:50,078 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:50] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 17:59:50,118 - INFO - 172.16.12.13 - - [04/Nov/2024 17:59:50] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:05:23,713 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:05:23,713 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:05:23,714 - INFO -  * Restarting with stat
2024-11-04 18:05:26,028 - WARNING -  * Debugger is active!
2024-11-04 18:05:26,035 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:05:30,611 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:30] "GET / HTTP/1.1" 200 -
2024-11-04 18:05:30,706 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:30] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 18:05:36,408 - INFO - User 'zura' logged in successfully.
2024-11-04 18:05:36,410 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:36] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:05:36,418 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:36] "GET /index HTTP/1.1" 200 -
2024-11-04 18:05:36,582 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:36] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:05:44,890 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 18:05:44,896 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:44] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:05:44,898 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:05:44,915 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:44] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:05:44,916 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:44] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:05:44,926 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:44] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:05:44,987 - INFO - 172.16.12.13 - - [04/Nov/2024 18:05:44] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:05:56,954 - INFO - Flask application is shutting down.
2024-11-04 18:05:57,066 - INFO - Flask application is shutting down.
2024-11-04 18:06:00,541 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:06:00,542 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:06:00,543 - INFO -  * Restarting with stat
2024-11-04 18:06:02,271 - WARNING -  * Debugger is active!
2024-11-04 18:06:02,278 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:06:43,979 - INFO - Flask application is shutting down.
2024-11-04 18:06:44,091 - INFO - Flask application is shutting down.
2024-11-04 18:06:53,740 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:06:53,740 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:06:53,742 - INFO -  * Restarting with stat
2024-11-04 18:06:55,456 - WARNING -  * Debugger is active!
2024-11-04 18:06:55,463 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:06:58,457 - INFO - 172.16.12.13 - - [04/Nov/2024 18:06:58] "GET / HTTP/1.1" 200 -
2024-11-04 18:07:03,595 - INFO - User 'zura' logged in successfully.
2024-11-04 18:07:03,596 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:03] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:07:03,603 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:03] "GET /index HTTP/1.1" 200 -
2024-11-04 18:07:03,686 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:03] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:07:10,903 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 18:07:10,907 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:10] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:07:10,909 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:07:10,928 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:10] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:07:10,929 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:10] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:07:10,937 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:10] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:07:10,952 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:10] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:07:20,842 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:20] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:07:27,903 - INFO - Data range selected: 2024-01-04 to 2024-11-04 with filter: both
2024-11-04 18:07:27,908 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:27] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:07:27,910 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:07:27,929 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:07:27,930 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:07:27,938 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:07:27,946 - INFO - 172.16.12.13 - - [04/Nov/2024 18:07:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:08:03,898 - INFO - Flask application is shutting down.
2024-11-04 18:08:04,019 - INFO - Flask application is shutting down.
2024-11-04 18:08:06,048 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:08:06,048 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:08:06,049 - INFO -  * Restarting with stat
2024-11-04 18:08:07,679 - WARNING -  * Debugger is active!
2024-11-04 18:08:07,685 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:08:15,385 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:15] "GET / HTTP/1.1" 200 -
2024-11-04 18:08:15,456 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 18:08:20,134 - INFO - User 'zura' logged in successfully.
2024-11-04 18:08:20,136 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:20] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:08:20,143 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:20] "GET /index HTTP/1.1" 200 -
2024-11-04 18:08:20,234 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:20] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:08:27,806 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 18:08:27,811 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:27] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:08:27,813 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 291, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't open named pipe to host: .  pipe: MySQL (2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 11, in fetch_data_from_db
    connection = mysql.connector.connect(**connection_parmeters)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 120, in __init__
    self.connect(**kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\abstracts.py", line 1181, in connect
    self._open_connection()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\mysql\connector\connection_cext.py", line 298, in _open_connection
    ) from err
mysql.connector.errors.DatabaseError: 2017 (HY000): Can't open named pipe to host: .  pipe: MySQL (2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 18, in fetch_data_from_db
    print(f"Error: {e}")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 35, in create_map
    df = fetch_data_from_db()
  File "E:\ZURA KOPADZE\mapping_stca\DBM\Connect_to_DBM.py", line 21, in fetch_data_from_db
    if connection.is_connected():
UnboundLocalError: local variable 'connection' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:08:27,829 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:08:27,830 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:08:27,871 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:08:27,896 - INFO - 127.0.0.1 - - [04/Nov/2024 18:08:27] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:09:50,746 - INFO - Flask application is shutting down.
2024-11-04 18:09:50,864 - INFO - Flask application is shutting down.
2024-11-04 18:09:51,894 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 18:09:52,122 - INFO -  * Restarting with stat
2024-11-04 18:09:54,129 - WARNING -  * Debugger is active!
2024-11-04 18:09:54,136 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:09:54,137 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:09:54,137 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:09:54,138 - INFO -  * Restarting with stat
2024-11-04 18:09:55,881 - WARNING -  * Debugger is active!
2024-11-04 18:09:55,887 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:09:59,813 - INFO - 172.16.12.13 - - [04/Nov/2024 18:09:59] "GET / HTTP/1.1" 200 -
2024-11-04 18:10:05,490 - INFO - User 'zura' logged in successfully.
2024-11-04 18:10:05,492 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:05] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:10:05,509 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:05] "GET /index HTTP/1.1" 200 -
2024-11-04 18:10:05,604 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:05] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:10:12,566 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 18:10:13,580 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:13] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:10:13,582 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 121, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 119, in create_map
    print(f"Map has been saved as '{output_file}'.")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:10:13,600 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:13] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:10:13,601 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:13] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:10:13,637 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:13] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:10:13,673 - INFO - 172.16.12.13 - - [04/Nov/2024 18:10:13] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:11:11,331 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\main.py', reloading
2024-11-04 18:11:11,468 - INFO -  * Restarting with stat
2024-11-04 18:11:11,524 - INFO -  * Detected change in 'E:\\ZURA KOPADZE\\mapping_stca\\create_map.py', reloading
2024-11-04 18:11:11,692 - INFO -  * Restarting with stat
2024-11-04 18:11:14,132 - WARNING -  * Debugger is active!
2024-11-04 18:11:14,144 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:11:14,145 - WARNING -  * Debugger is active!
2024-11-04 18:11:14,152 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:11:18,013 - INFO - Flask application is shutting down.
2024-11-04 18:11:18,125 - INFO - Flask application is shutting down.
2024-11-04 18:11:21,140 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:11:21,140 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:11:21,141 - INFO -  * Restarting with stat
2024-11-04 18:11:22,844 - WARNING -  * Debugger is active!
2024-11-04 18:11:22,851 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:11:26,230 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:26] "GET / HTTP/1.1" 200 -
2024-11-04 18:11:26,346 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 18:11:32,433 - INFO - User 'zura' logged in successfully.
2024-11-04 18:11:32,435 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:11:32,453 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:32] "GET /index HTTP/1.1" 200 -
2024-11-04 18:11:32,632 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:32] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:11:40,496 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 18:11:41,514 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:41] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-11-04 18:11:41,516 - ERROR - Error on request:
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 329, in debug_application
    app_iter = self.app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 123, in index
    real_percentage, suspicious_percentage, warning_message = create_map(start_date, end_date, callsign_filter)
  File "E:\ZURA KOPADZE\mapping_stca\create_map.py", line 119, in create_map
    print(f"Map has been saved as '{output_file}'.")
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    for data in application_iter:
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\werkzeug\debug\__init__.py", line 364, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [Errno 22] Invalid argument
2024-11-04 18:11:41,528 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:41] "[36mGET /index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-11-04 18:11:41,528 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:41] "[36mGET /index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-11-04 18:11:41,541 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:41] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:11:41,589 - INFO - 172.16.12.13 - - [04/Nov/2024 18:11:41] "[36mGET /index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-11-04 18:20:30,067 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 18:20:30,068 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 18:20:30,070 - INFO -  * Restarting with stat
2024-11-04 18:20:31,621 - WARNING -  * Debugger is active!
2024-11-04 18:20:31,683 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 18:21:06,626 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:06] "GET / HTTP/1.1" 200 -
2024-11-04 18:21:06,885 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-11-04 18:21:18,814 - INFO - User 'zura' logged in successfully.
2024-11-04 18:21:18,829 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:18] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 18:21:18,909 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:18] "GET /index HTTP/1.1" 200 -
2024-11-04 18:21:19,399 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:19] "[36mGET /static/favicon.ico HTTP/1.1[0m" 304 -
2024-11-04 18:21:25,718 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 18:21:26,855 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:26] "POST /index HTTP/1.1" 200 -
2024-11-04 18:21:26,898 - INFO - 127.0.0.1 - - [04/Nov/2024 18:21:26] "GET /Results/map.html HTTP/1.1" 200 -
2024-11-04 20:01:56,917 - INFO - Flask application is shutting down.
2024-11-04 20:01:57,083 - INFO - Flask application is shutting down.
2024-11-04 20:18:05,506 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-11-04 20:18:05,506 - INFO - [33mPress CTRL+C to quit[0m
2024-11-04 20:18:05,507 - INFO -  * Restarting with stat
2024-11-04 20:18:07,345 - WARNING -  * Debugger is active!
2024-11-04 20:18:07,351 - INFO -  * Debugger PIN: 334-236-534
2024-11-04 20:18:27,007 - INFO - 127.0.0.1 - - [04/Nov/2024 20:18:27] "GET / HTTP/1.1" 200 -
2024-11-04 20:18:34,037 - INFO - User 'zura' logged in successfully.
2024-11-04 20:18:34,039 - INFO - 127.0.0.1 - - [04/Nov/2024 20:18:34] "[32mPOST / HTTP/1.1[0m" 302 -
2024-11-04 20:18:34,057 - INFO - 127.0.0.1 - - [04/Nov/2024 20:18:34] "GET /index HTTP/1.1" 200 -
2024-11-04 20:18:44,055 - INFO - Data range selected: 2024-01-04 to 2024-12-04 with filter: both
2024-11-04 20:18:45,090 - INFO - 127.0.0.1 - - [04/Nov/2024 20:18:45] "POST /index HTTP/1.1" 200 -
2024-11-04 20:18:45,122 - INFO - 127.0.0.1 - - [04/Nov/2024 20:18:45] "GET /Results/map.html HTTP/1.1" 200 -
